### ISSUE TITLE
Image size optimization

### ISSUE THREAD

**Issue by ddrozdov** [krizsan/elastalert-docker#2]
Please merge two RUN commands into a single one to get rid of python-dev in the intermediate layer.
Please also add `&& rm -rf /var/lib/apt/lists/*` after `apt-get install`. This would reduce the size of the intermediate layer by ~20Mb.

**Comment by krizsan** [comment]
Line 96 (master branch) already contain this:
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
Different work-directories are used for the two RUN commands.
To reduce the size of the image, I would look into http://www.iron.io.
Do submit a pull request if you have any improvements!

**Comment by ddrozdov** [comment]
Line 96 is in another RUN, so it won't reduce the size of first RUN's layer in any way.
Working directory can be changed with the `cd` shell command.

**Comment by krizsan** [comment]
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#workdir:238d508e032e5771326119b3d1c5c7a0

**Comment by ddrozdov** [comment]
That's true when `cd` is the first command in a sequence, but in your case `WORKDIR` splits what could be a single `RUN` into two `RUN`'s that adds an additional unnecessary layer.

**Comment by krizsan** [comment]
From 158M to 63M, with the "unnecessary layer". Enjoy!
